// vibecode-main-corrected/vibecode-starters/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [],
  template: `
    <div class="container">
      <header>
        <h1>Welcome to Angular!</h1>
        <img src="/angular.svg" alt="Angular Logo" class="logo" />
      </header>
      
      <main>
        <p>This is a basic Angular starter template.</p>
        <div class="counter">
          <button (click)="decrement()">-</button>
          <span>{{ count }}</span>
          <button (click)="increment()">+</button>
        </div>
        <p>Count: {{ count }}</p>
      </main>
      
      <footer>
        <p>Built with Angular {{ angularVersion }}</p>
      </footer>
    </div>
  `,
  styles: [`
    .container {
      max-width: 800px;
      margin: 0 auto;
      padding: 2rem;
      text-align: center;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    }
    
    .logo {
      height: 6rem;
      margin: 1rem 0;
    }
    
    h1 {
      color: #dd0031;
      margin-bottom: 1rem;
    }
    
    .counter {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 1rem;
      margin: 2rem 0;
    }
    
    button {
      background: #dd0031;
      color: white;
      border: none;
      padding: 0.5rem 1rem;
      border-radius: 4px;
      cursor: pointer;
      font-size: 1.2rem;
    }
    
    button:hover {
      background: #c50025;
    }
    
    span {
      font-size: 1.5rem;
      font-weight: bold;
      min-width: 3rem;
    }
    
    footer {
      margin-top: 2rem;
      color: #666;
    }
  `]
})
export class AppComponent {
  title = 'angular-starter';
  count = 0;
  angularVersion = '17';
  
  increment() {
    this.count++;
  }
  
  decrement() {
    this.count--;
  }
}

// vibecode-main-corrected/vibecode-starters/vue/src/App.vue
<template>
  <div id="app">
    <header>
      <h1>Vue.js Starter</h1>
      <p>Welcome to your Vue.js application!</p>
    </header>
    
    <main>
      <div class="card">
        <h2>Getting Started</h2>
        <p>Edit <code>src/App.vue</code> to get started.</p>
        <button @click="count++" class="btn">
          Count is: {{ count }}
        </button>
      </div>
    </main>
  </div>
</template>

<script>
import { ref } from 'vue'

export default {
  name: 'App',
  setup() {
    const count = ref(0)
    
    return {
      count
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

.card {
  padding: 2rem;
  margin: 2rem auto;
  max-width: 600px;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.btn {
  background-color: #42b883;
  color: white;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  cursor: pointer;
  font-size: 1rem;
}

.btn:hover {
  background-color: #369870;
}

code {
  background-color: #f1f5f9;
  padding: 0.2rem 0.4rem;
  border-radius: 3px;
  font-family: 'Courier New', monospace;
}
</style>
